// this file is generated by relog-rsbuild-plugin 
    // Do not edit
    (() => {
        'background only';
        if(!globalThis.Request) return;
        const request = new Request("https://sadsadadasd.ngrok-free.app");
        // const request = "/log";
    
        globalThis.console.log = (...message) => {
            fetch(request, {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                },
                body: JSON.stringify({ message }),
            })
        }
        globalThis.console.info = (...message) => {
            fetch(request, {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                },
                body: JSON.stringify({ message }),
            })
        }
    })()