import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
const __dirname = path.dirname(fileURLToPath(import.meta.url))

console.log(__dirname, "generate")

export function createTemplateFile(url:string) {

    const  template = `// this file is generated by relog-rsbuild-plugin 
    // Do not edit
    (() => {
        'background only';
        if(!globalThis.Request) return;
        const request = new Request("${url}/console_log");
        // const request = "/log";
    
        globalThis.console.log = (...message) => {
            fetch(request, {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                },
                body: JSON.stringify({ message }),
            })
        }
        globalThis.console.info = (...message) => {
            fetch(request, {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                },
                body: JSON.stringify({ message }),
            })
        }
    })()`
    
    fs.writeFileSync(path.join(__dirname, 'console.js'), template)
    
    }